# 머신 러닝 교과서 3판

# 14장 - 텐서플로의 구조 자세히 알아보기 (2/3)

**아래 링크를 통해 이 노트북을 주피터 노트북 뷰어(nbviewer.jupyter.org)로 보거나 구글 코랩(colab.research.google.com)에서 실행할 수 있습니다.**

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://nbviewer.org/github/rickiepark/python-machine-learning-book-3rd-edition/blob/master/ch14/ch14_part2.ipynb"><img src="https://jupyter.org/assets/share.png" width="60" />주피터 노트북 뷰어로 보기</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/rickiepark/python-machine-learning-book-3rd-edition/blob/master/ch14/ch14_part2.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />구글 코랩(Colab)에서 실행하기</a>
  </td>
</table>

### 목차

- 텐서플로 추정기
  - 특성 열 사용하기
  - 사전에 준비된 추정기로 머신 러닝 수행하기

In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd

from IPython.display import Image

In [2]:
tf.__version__

'2.19.0'

## 텐서플로 추정기

##### 사전에 준비된 추정기 사용하는 단계

 * **단계 1:** 데이터 로딩을 위해 입력 함수 정의하기
 * **단계 2:** 추정기와 데이터 사이를 연결하기 위해 특성 열 정의하기
 * **단계 3:** 추정기 객체를 만들거나 케라스 모델을 추정기로 바꾸기
 * **단계 4:** 추정기 사용하기: train() evaluate() predict()

In [3]:
tf.random.set_seed(1)
np.random.seed(1)

### 특성 열 사용하기


 * 정의: https://developers.google.com/machine-learning/glossary/#feature_columns
 * 문서: https://www.tensorflow.org/api_docs/python/tf/feature_column

In [4]:
Image(url='https://git.io/JL56E', width=700)

In [6]:
dataset_path = tf.keras.utils.get_file("auto-mpg.data",
                                       ("http://archive.ics.uci.edu/ml/machine-learning-databases"
                                        "/auto-mpg/auto-mpg.data"))

column_names = ['MPG', 'Cylinders', 'Displacement', 'Horsepower',
                'Weight', 'Acceleration', 'ModelYear', 'Origin']

df = pd.read_csv(dataset_path, names=column_names,
                 na_values = "?", comment='\t',
                 sep=" ", skipinitialspace=True)

df.tail()

Downloading data from http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data
  16384/Unknown 0s 9us/step

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,ModelYear,Origin
393,27.0,4,140.0,86.0,2790.0,15.6,82,1
394,44.0,4,97.0,52.0,2130.0,24.6,82,2
395,32.0,4,135.0,84.0,2295.0,11.6,82,1
396,28.0,4,120.0,79.0,2625.0,18.6,82,1
397,31.0,4,119.0,82.0,2720.0,19.4,82,1

In [7]:
print(df.isna().sum())

df = df.dropna()
df = df.reset_index(drop=True)
df.tail()

MPG             0
Cylinders       0
Displacement    0
Horsepower      6
Weight          0
Acceleration    0
ModelYear       0
Origin          0
dtype: int64

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,ModelYear,Origin
387,27.0,4,140.0,86.0,2790.0,15.6,82,1
388,44.0,4,97.0,52.0,2130.0,24.6,82,2
389,32.0,4,135.0,84.0,2295.0,11.6,82,1
390,28.0,4,120.0,79.0,2625.0,18.6,82,1
391,31.0,4,119.0,82.0,2720.0,19.4,82,1

In [8]:
import sklearn
import sklearn.model_selection


df_train, df_test = sklearn.model_selection.train_test_split(df, train_size=0.8)
train_stats = df_train.describe().transpose()
train_stats

,count,mean,std,min,25%,50%,75%,max
MPG,313.0,23.404153,7.666909,9.0,17.5,23.0,29.0,46.6
Cylinders,313.0,5.402556,1.701506,3.0,4.0,4.0,8.0,8.0
Displacement,313.0,189.512780,102.675646,68.0,104.0,140.0,260.0,455.0
Horsepower,313.0,102.929712,37.919046,46.0,75.0,92.0,120.0,230.0
Weight,313.0,2961.198083,848.602146,1613.0,2219.0,2755.0,3574.0,5140.0
Acceleration,313.0,15.704473,2.725399,8.5,14.0,15.5,17.3,24.8
ModelYear,313.0,75.929712,3.675305,70.0,73.0,76.0,79.0,82.0
Origin,313.0,1.591054,0.807923,1.0,1.0,1.0,2.0,3.0

In [9]:
numeric_column_names = ['Cylinders', 'Displacement', 'Horsepower', 'Weight', 'Acceleration']

df_train_norm, df_test_norm = df_train.copy(), df_test.copy()

for col_name in numeric_column_names:
    mean = train_stats.loc[col_name, 'mean']
    std  = train_stats.loc[col_name, 'std']
    df_train_norm.loc[:, col_name] = (df_train_norm.loc[:, col_name] - mean)/std
    df_test_norm.loc[:, col_name] = (df_test_norm.loc[:, col_name] - mean)/std

df_train_norm.tail()

/tmp/ipython-input-487790972.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.8243028   0.3511267  -0.8243028  -0.8243028  -0.8243028   1.52655621
  0.3511267  -0.8243028  -0.8243028  -0.8243028   0.3511267  -0.8243028
  0.3511267   1.52655621  1.52655621  1.52655621  0.3511267   1.52655621
 -0.8243028   0.3511267   1.52655621 -0.8243028  -0.8243028   0.3511267
 -0.8243028  -0.8243028  -0.8243028   0.3511267  -0.8243028   1.52655621
  0.3511267  -0.8243028   0.3511267  -0.8243028  -0.8243028   1.52655621
 -0.8243028   1.52655621  1.52655621 -0.8243028  -0.8243028  -0.8243028
 -0.8243028   0.3511267  -0.8243028   1.52655621 -0.8243028  -0.8243028
  1.52655621 -0.8243028  -0.8243028  -0.8243028   1.52655621  1.52655621
  0.3511267   0.3511267   1.52655621 -0.8243028  -0.8243028   1.52655621
  1.52655621 -0.8243028  -0.8243028   0.3511267   1.52655621 -0.8243028
  0.3511267  -0.8243028   1.52655621  1.52655621 -0.8243028  -0.8243028
 -1.41201755  1.52655621  0.3511267   1.52655621 -0.8243028  -0.8243028
 -0.8243028   1.52655621  1.52655621  0.3511267   0.3511267   1.52655621
 -0.8243028   1.52655621 -0.23658805 -0.8243028  -0.8243028   0.3511267
  0.3511267  -1.41201755 -0.8243028   1.52655621 -0.8243028   1.52655621
 -0.8243028   1.52655621  0.3511267  -0.8243028   0.3511267  -1.41201755
  0.3511267  -0.8243028  -0.8243028  -0.8243028  -0.8243028  -0.8243028
 -0.8243028   1.52655621  1.52655621 -0.8243028   0.3511267  -0.8243028
 -0.8243028   0.3511267   1.52655621 -0.8243028  -0.8243028   0.3511267
  0.3511267  -0.8243028  -0.8243028  -0.23658805 -0.8243028   0.3511267
  0.3511267   0.3511267  -0.8243028   1.52655621  1.52655621 -0.8243028
  0.3511267   1.52655621  1.52655621 -0.8243028   0.3511267   0.3511267
 -0.8243028  -0.8243028  -0.8243028  -0.8243028   1.52655621 -0.8243028
 -0.8243028   0.3511267  -0.8243028  -0.8243028   1.52655621 -0.8243028
  1.52655621 -0.8243028  -0.8243028   1.52655621  1.52655621 -0.8243028
  0.3511267  -0.8243028   1.52655621  0.3511267  -0.8243028   1.52655621
 -0.8243028  -0.8243028   1.52655621  1.52655621 -0.8243028   1.52655621
  0.3511267  -0.8243028  -0.8243028   0.3511267   1.52655621  1.52655621
 -0.8243028  -0.8243028  -0.8243028  -0.8243028  -0.8243028  -0.8243028
 -0.8243028   1.52655621 -0.8243028   0.3511267   1.52655621 -0.8243028
 -0.23658805 -0.8243028  -0.8243028  -0.8243028  -0.8243028  -0.8243028
  0.3511267  -0.8243028  -0.8243028   1.52655621  1.52655621 -0.8243028
  1.52655621 -0.8243028   1.52655621 -0.8243028  -0.8243028  -0.8243028
 -0.8243028   0.3511267  -0.8243028   1.52655621 -0.8243028   0.3511267
  1.52655621 -0.8243028  -0.8243028  -0.8243028   0.3511267  -0.8243028
 -0.8243028  -0.8243028  -0.8243028   0.3511267  -0.8243028   1.52655621
 -0.8243028  -0.8243028  -0.8243028   1.52655621 -0.8243028   1.52655621
 -0.8243028   0.3511267  -0.8243028   0.3511267  -0.8243028  -0.8243028
  0.3511267   1.52655621 -0.8243028   0.3511267   1.52655621  0.3511267
 -0.8243028  -0.8243028  -0.8243028   1.52655621  1.52655621 -0.8243028
 -0.8243028  -0.8243028   1.52655621  0.3511267   0.3511267  -0.8243028
 -0.8243028  -0.8243028   1.52655621  0.3511267   0.3511267   0.3511267
  1.52655621 -0.8243028   1.52655621  0.3511267  -0.8243028  -0.8243028
 -0.8243028  -0.8243028   1.52655621 -0.8243028   1.52655621 -0.8243028
  1.52655621 -0.8243028  -0.8243028  -0.8243028  -0.8243028  -0.8243028
  1.52655621 -0.8243028  -0.8243028  -0.8243028   0.3511267  -0.8243028
  1.52655621 -0.8243028  -0.8243028  -0.8243028  -0.8243028   1.52655621
 -0.8243028   1.52655621 -0.8243028  -1.41201755 -0.8243028   1.52655621
 -0.8243028   1.52655621  0.3511267   0.3511267   0.3511267  -0.8243028
 -0.8243028   0.3511267  -0.8243028   1.52655621 -0.8243028  -0.8243028
 -0.8243028   0.3511267  -0.8243028   0.3511267   1.52655621 -0.8243028
  1.52655621]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_train_norm.loc[:, col_name] = (df_train_norm.loc[:, col_name] - mean)/std
/tmp/ipython-input-487790972.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.8243028  -0.8243028  -0.8243028  -0.8243028  -0.8243028  -0.8243028
 -0.8243028   1.52655621 -0.8243028  -0.8243028   0.3511267  -0.8243028
  1.52655621 -0.8243028  -0.8243028   1.52655621 -0.8243028  -0.8243028
  1.52655621  0.3511267  -0.8243028   0.3511267   1.52655621  1.52655621
  1.52655621  1.52655621 -0.8243028   0.3511267   0.3511267  -0.8243028
  1.52655621 -0.8243028   1.52655621  0.3511267   0.3511267   1.52655621
  0.3511267   0.3511267  -0.8243028  -0.8243028   1.52655621  1.52655621
  0.3511267   0.3511267   0.3511267   0.3511267   1.52655621 -0.8243028
  0.3511267   1.52655621  1.52655621  0.3511267  -0.8243028  -0.8243028
 -0.8243028   0.3511267   0.3511267   0.3511267  -0.8243028  -0.8243028
  0.3511267  -0.8243028  -0.8243028   1.52655621  0.3511267   0.3511267
 -0.8243028   1.52655621 -0.8243028   1.52655621 -0.8243028   1.52655621
  1.52655621 -0.8243028  -0.8243028  -0.8243028   1.52655621  1.52655621
  1.52655621]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_test_norm.loc[:, col_name] = (df_test_norm.loc[:, col_name] - mean)/std

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,ModelYear,Origin
203,28.0,-0.824303,-0.901020,-0.736562,-0.950031,0.255202,76,3
255,19.4,0.351127,0.413800,-0.340982,0.293190,0.548737,78,1
72,13.0,1.526556,1.144256,0.713897,1.339617,-0.625403,72,1
235,30.5,-0.824303,-0.891280,-1.053025,-1.072585,0.475353,77,1
37,14.0,1.526556,1.563051,1.636916,1.470420,-1.359240,71,1

#### 수치형 열

In [10]:
numeric_features = []

for col_name in numeric_column_names:
    numeric_features.append(tf.feature_column.numeric_column(key=col_name))

numeric_features

WARNING:tensorflow:From /tmp/ipython-input-2109796009.py:4: numeric_column (from tensorflow.python.feature_column.feature_column_v2) is deprecated and will be removed in a future version.
Instructions for updating:
Use Keras preprocessing layers instead, either directly or via the `tf.keras.utils.FeatureSpace` utility. Each of `tf.feature_column.*` has a functional equivalent in `tf.keras.layers` for feature preprocessing when training a Keras model.

[NumericColumn(key='Cylinders', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='Displacement', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='Horsepower', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='Weight', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='Acceleration', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [11]:
feature_year = tf.feature_column.numeric_column(key="ModelYear")

bucketized_features = []

bucketized_features.append(tf.feature_column.bucketized_column(
    source_column=feature_year,
    boundaries=[73, 76, 79]))

print(bucketized_features)

WARNING:tensorflow:From /tmp/ipython-input-1410326794.py:5: bucketized_column (from tensorflow.python.feature_column.feature_column_v2) is deprecated and will be removed in a future version.
Instructions for updating:
Use Keras preprocessing layers instead, either directly or via the `tf.keras.utils.FeatureSpace` utility. Each of `tf.feature_column.*` has a functional equivalent in `tf.keras.layers` for feature preprocessing when training a Keras model.

[BucketizedColumn(source_column=NumericColumn(key='ModelYear', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), boundaries=(73, 76, 79))]

In [12]:
feature_origin = tf.feature_column.categorical_column_with_vocabulary_list(
    key='Origin',
    vocabulary_list=[1, 2, 3])

categorical_indicator_features = []
categorical_indicator_features.append(tf.feature_column.indicator_column(feature_origin))

print(categorical_indicator_features)

WARNING:tensorflow:From /tmp/ipython-input-4078329294.py:1: categorical_column_with_vocabulary_list (from tensorflow.python.feature_column.feature_column_v2) is deprecated and will be removed in a future version.
Instructions for updating:
Use Keras preprocessing layers instead, either directly or via the `tf.keras.utils.FeatureSpace` utility. Each of `tf.feature_column.*` has a functional equivalent in `tf.keras.layers` for feature preprocessing when training a Keras model.
WARNING:tensorflow:From /tmp/ipython-input-4078329294.py:6: indicator_column (from tensorflow.python.feature_column.feature_column_v2) is deprecated and will be removed in a future version.
Instructions for updating:
Use Keras preprocessing layers instead, either directly or via the `tf.keras.utils.FeatureSpace` utility. Each of `tf.feature_column.*` has a functional equivalent in `tf.keras.layers` for feature preprocessing when training a Keras model.

[IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='Origin', vocabulary_list=(1, 2, 3), dtype=tf.int64, default_value=-1, num_oov_buckets=0))]

### 사전에 준비된 추정기로 머신러닝 수행하기

In [13]:
def train_input_fn(df_train, batch_size=8):
    df = df_train.copy()
    train_x, train_y = df, df.pop('MPG')
    dataset = tf.data.Dataset.from_tensor_slices((dict(train_x), train_y))

    # 셔플, 반복, 배치
    return dataset.shuffle(1000).repeat().batch(batch_size)

## 조사
ds = train_input_fn(df_train_norm)
batch = next(iter(ds))
print('키:', batch[0].keys())
print('ModelYear:', batch[0]['ModelYear'])

키: dict_keys(['Cylinders', 'Displacement', 'Horsepower', 'Weight', 'Acceleration', 'ModelYear', 'Origin'])
ModelYear: tf.Tensor([82 78 76 72 78 73 70 78], shape=(8,), dtype=int64)

In [14]:
all_feature_columns = (numeric_features +
                       bucketized_features +
                       categorical_indicator_features)

print(all_feature_columns)

[NumericColumn(key='Cylinders', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='Displacement', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='Horsepower', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='Weight', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='Acceleration', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), BucketizedColumn(source_column=NumericColumn(key='ModelYear', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), boundaries=(73, 76, 79)), IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='Origin', vocabulary_list=(1, 2, 3), dtype=tf.int64, default_value=-1, num_oov_buckets=0))]

**최신 텐서플로에서 `tf.estimator`가 삭제되어 더이상 사용할 수 없습니다.**

In [ ]:
# regressor = tf.estimator.DNNRegressor(
#     feature_columns=all_feature_columns,
#     hidden_units=[32, 10],
#     model_dir='models/autompg-dnnregressor/')

In [ ]:
# EPOCHS = 1000
# BATCH_SIZE = 8
# total_steps = EPOCHS * int(np.ceil(len(df_train) / BATCH_SIZE))
# print('훈련 스텝:', total_steps)

# regressor.train(
#     input_fn=lambda:train_input_fn(df_train_norm, batch_size=BATCH_SIZE),
#     steps=total_steps)

In [ ]:
# reloaded_regressor = tf.estimator.DNNRegressor(
#     feature_columns=all_feature_columns,
#     hidden_units=[32, 10],
#     warm_start_from='models/autompg-dnnregressor/',
#     model_dir='models/autompg-dnnregressor/')

In [ ]:
# def eval_input_fn(df_test, batch_size=8):
#     df = df_test.copy()
#     test_x, test_y = df, df.pop('MPG')
#     dataset = tf.data.Dataset.from_tensor_slices((dict(test_x), test_y))

#     return dataset.batch(batch_size)

# eval_results = reloaded_regressor.evaluate(
#     input_fn=lambda:eval_input_fn(df_test_norm, batch_size=8))

# for key in eval_results:
#     print('{:15s} {}'.format(key, eval_results[key]))

# print('평균 손실 {:.4f}'.format(eval_results['average_loss']))

In [ ]:
# pred_res = regressor.predict(input_fn=lambda: eval_input_fn(df_test_norm, batch_size=8))

# print(next(iter(pred_res)))

#### Boosted Tree Regressor

In [ ]:
# boosted_tree = tf.estimator.BoostedTreesRegressor(
#     feature_columns=all_feature_columns,
#     n_batches_per_layer=20,
#     n_trees=200)

# boosted_tree.train(
#     input_fn=lambda:train_input_fn(df_train_norm, batch_size=BATCH_SIZE))

# eval_results = boosted_tree.evaluate(
#     input_fn=lambda:eval_input_fn(df_test_norm, batch_size=8))

# print(eval_results)

# print('평균 손실 {:.4f}'.format(eval_results['average_loss']))